// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibb/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the ibb module's genesis state.
type GenesisState struct {
	// this line is used by starport scaffolding # genesis/proto/state
	RepayList    []*Repay    `protobuf:"bytes,10,rep,name=repayList,proto3" json:"repayList,omitempty"`
	WithdrawList []*Withdraw `protobuf:"bytes,9,rep,name=withdrawList,proto3" json:"withdrawList,omitempty"`
	UserList     []*User     `protobuf:"bytes,7,rep,name=userList,proto3" json:"userList,omitempty"`
	UserCount    uint64      `protobuf:"varint,8,opt,name=userCount,proto3" json:"userCount,omitempty"`
	BorrowList   []*Borrow   `protobuf:"bytes,5,rep,name=borrowList,proto3" json:"borrowList,omitempty"`
	BorrowCount  uint64      `protobuf:"varint,6,opt,name=borrowCount,proto3" json:"borrowCount,omitempty"`
	DepositList  []*Deposit  `protobuf:"bytes,3,rep,name=depositList,proto3" json:"depositList,omitempty"`
	DepositCount uint64      `protobuf:"varint,4,opt,name=depositCount,proto3" json:"depositCount,omitempty"`
	PoolList     []*Pool     `protobuf:"bytes,1,rep,name=poolList,proto3" json:"poolList,omitempty"`
	PoolCount    uint64      `protobuf:"varint,2,opt,name=poolCount,proto3" json:"poolCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb06c88d50ffbe7d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetRepayList() []*Repay {
	if m != nil {
		return m.RepayList
	}
	return nil
}

func (m *GenesisState) GetWithdrawList() []*Withdraw {
	if m != nil {
		return m.WithdrawList
	}
	return nil
}

func (m *GenesisState) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GenesisState) GetUserCount() uint64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *GenesisState) GetBorrowList() []*Borrow {
	if m != nil {
		return m.BorrowList
	}
	return nil
}

func (m *GenesisState) GetBorrowCount() uint64 {
	if m != nil {
		return m.BorrowCount
	}
	return 0
}

func (m *GenesisState) GetDepositList() []*Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *GenesisState) GetPoolList() []*Pool {
	if m != nil {
		return m.PoolList
	}
	return nil
}

func (m *GenesisState) GetPoolCount() uint64 {
	if m != nil {
		return m.PoolCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sapienscosmos.ibb.ibb.GenesisState")
}

func init() { proto.RegisterFile("ibb/genesis.proto", fileDescriptor_fb06c88d50ffbe7d) }

var fileDescriptor_fb06c88d50ffbe7d = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0x02, 0x41,
	0x18, 0x76, 0xd3, 0x4c, 0x47, 0xe9, 0x63, 0x20, 0x10, 0xb3, 0x4d, 0x3c, 0xd9, 0xa1, 0x15, 0xea,
	0x10, 0x04, 0x41, 0x68, 0xd0, 0xa5, 0x43, 0x4c, 0x44, 0xd0, 0x6d, 0x47, 0x07, 0x1d, 0x50, 0x67,
	0x99, 0x19, 0x31, 0xef, 0xfd, 0x80, 0x7e, 0x56, 0x47, 0x8f, 0x1d, 0x43, 0xff, 0x48, 0xbc, 0xef,
	0xac, 0xba, 0x42, 0xdb, 0x61, 0x97, 0x79, 0x1f, 0x9e, 0x8f, 0x77, 0x9f, 0x1d, 0x72, 0x24, 0x39,
	0x6f, 0xf5, 0xc5, 0x58, 0x18, 0x69, 0x82, 0x48, 0x2b, 0xab, 0xe8, 0xb1, 0x09, 0x23, 0x29, 0xc6,
	0xa6, 0xab, 0xcc, 0x48, 0x99, 0x40, 0x72, 0x0e, 0x4f, 0xf5, 0x00, 0x98, 0x5a, 0x44, 0xe1, 0xcc,
	0xf1, 0xaa, 0x14, 0x80, 0xa9, 0xb4, 0x83, 0x9e, 0x0e, 0xa7, 0x31, 0xb6, 0x0f, 0xd8, 0xc4, 0x08,
	0x1d, 0xcf, 0x87, 0x30, 0x73, 0xa5, 0xb5, 0x5a, 0x31, 0x30, 0xb0, 0x27, 0x22, 0x65, 0xa4, 0x4d,
	0x8a, 0x22, 0xa5, 0x86, 0x6e, 0x6e, 0x7c, 0xe4, 0x48, 0xf9, 0xc1, 0xad, 0xf4, 0x6c, 0x43, 0x2b,
	0xe8, 0x0d, 0x29, 0x62, 0xf0, 0xa3, 0x34, 0xb6, 0x42, 0xea, 0xd9, 0x66, 0xe9, 0xb2, 0x16, 0xfc,
	0xb9, 0x65, 0xc0, 0x80, 0xc7, 0x36, 0x74, 0xda, 0x21, 0xe5, 0xd5, 0x8e, 0x28, 0x2f, 0xa2, 0xfc,
	0x2c, 0x45, 0xfe, 0x1a, 0x53, 0xd9, 0x96, 0x88, 0x5e, 0x93, 0x02, 0x7c, 0x14, 0x1a, 0xec, 0xa1,
	0xc1, 0x49, 0x8a, 0xc1, 0x8b, 0x11, 0x9a, 0xad, 0xc9, 0xb4, 0x46, 0x8a, 0x70, 0xee, 0xa8, 0xc9,
	0xd8, 0x56, 0x0a, 0x75, 0xaf, 0x99, 0x63, 0x1b, 0x80, 0xde, 0x12, 0xe2, 0xba, 0x41, 0xe3, 0x5d,
	0x34, 0x3e, 0x4d, 0x31, 0x6e, 0x23, 0x91, 0x25, 0x04, 0xb4, 0x4e, 0x4a, 0x6e, 0x72, 0xf6, 0x79,
	0xb4, 0x4f, 0x42, 0xf4, 0x8e, 0x94, 0xe2, 0xaa, 0x31, 0x21, 0x8b, 0x09, 0x7e, 0x4a, 0xc2, 0xbd,
	0x63, 0xb2, 0xa4, 0x84, 0x36, 0x48, 0x39, 0x1e, 0x5d, 0x48, 0x0e, 0x43, 0xb6, 0x30, 0x68, 0x07,
	0xfe, 0x1e, 0x46, 0x78, 0xff, 0xb6, 0xf3, 0xa4, 0xd4, 0x90, 0xad, 0xc9, 0xd0, 0x0e, 0x9c, 0x9d,
	0xf3, 0x8e, 0x6b, 0x67, 0x0d, 0xb4, 0x3b, 0x5f, 0x0b, 0xdf, 0x9b, 0x2f, 0x7c, 0xef, 0x67, 0xe1,
	0x7b, 0x9f, 0x4b, 0x3f, 0x33, 0x5f, 0xfa, 0x99, 0xef, 0xa5, 0x9f, 0x79, 0x3b, 0xef, 0x4b, 0x3b,
	0x98, 0xf0, 0xa0, 0xab, 0x46, 0xad, 0x38, 0xe8, 0xc2, 0x25, 0xb5, 0xe0, 0x2a, 0xbd, 0xe3, 0xdb,
	0xce, 0x22, 0x61, 0x78, 0x1e, 0xaf, 0xd4, 0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xff,
	0xbc, 0xb2, 0xe8, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RepayList) > 0 {
		for iNdEx := len(m.RepayList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RepayList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.WithdrawList) > 0 {
		for iNdEx := len(m.WithdrawList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.UserCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UserCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.UserList) > 0 {
		for iNdEx := len(m.UserList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.BorrowCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BorrowCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.BorrowList) > 0 {
		for iNdEx := len(m.BorrowList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BorrowList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.DepositCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PoolCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PoolCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolList) > 0 {
		for iNdEx := len(m.PoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolList) > 0 {
		for _, e := range m.PoolList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PoolCount != 0 {
		n += 1 + sovGenesis(uint64(m.PoolCount))
	}
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositCount))
	}
	if len(m.BorrowList) > 0 {
		for _, e := range m.BorrowList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BorrowCount != 0 {
		n += 1 + sovGenesis(uint64(m.BorrowCount))
	}
	if len(m.UserList) > 0 {
		for _, e := range m.UserList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.UserCount != 0 {
		n += 1 + sovGenesis(uint64(m.UserCount))
	}
	if len(m.WithdrawList) > 0 {
		for _, e := range m.WithdrawList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RepayList) > 0 {
		for _, e := range m.RepayList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolList = append(m.PoolList, &Pool{})
			if err := m.PoolList[len(m.PoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCount", wireType)
			}
			m.PoolCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, &Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCount", wireType)
			}
			m.DepositCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BorrowList = append(m.BorrowList, &Borrow{})
			if err := m.BorrowList[len(m.BorrowList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowCount", wireType)
			}
			m.BorrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserList = append(m.UserList, &User{})
			if err := m.UserList[len(m.UserList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserCount", wireType)
			}
			m.UserCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawList = append(m.WithdrawList, &Withdraw{})
			if err := m.WithdrawList[len(m.WithdrawList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepayList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepayList = append(m.RepayList, &Repay{})
			if err := m.RepayList[len(m.RepayList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
