// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibb/response.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LoadPoolResponse struct {
	Asset            string `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	CollatoralFactor int32  `protobuf:"varint,2,opt,name=CollatoralFactor,proto3" json:"CollatoralFactor,omitempty"`
	Liquidity        int32  `protobuf:"varint,3,opt,name=Liquidity,proto3" json:"Liquidity,omitempty"`
	DepositApy       int32  `protobuf:"varint,4,opt,name=DepositApy,proto3" json:"DepositApy,omitempty"`
	BorrowApy        int32  `protobuf:"varint,5,opt,name=BorrowApy,proto3" json:"BorrowApy,omitempty"`
	AssetPrice       int32  `protobuf:"varint,6,opt,name=AssetPrice,proto3" json:"AssetPrice,omitempty"`
}

func (m *LoadPoolResponse) Reset()         { *m = LoadPoolResponse{} }
func (m *LoadPoolResponse) String() string { return proto.CompactTextString(m) }
func (*LoadPoolResponse) ProtoMessage()    {}
func (*LoadPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{0}
}
func (m *LoadPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoadPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoadPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoadPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPoolResponse.Merge(m, src)
}
func (m *LoadPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoadPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPoolResponse proto.InternalMessageInfo

func (m *LoadPoolResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *LoadPoolResponse) GetCollatoralFactor() int32 {
	if m != nil {
		return m.CollatoralFactor
	}
	return 0
}

func (m *LoadPoolResponse) GetLiquidity() int32 {
	if m != nil {
		return m.Liquidity
	}
	return 0
}

func (m *LoadPoolResponse) GetDepositApy() int32 {
	if m != nil {
		return m.DepositApy
	}
	return 0
}

func (m *LoadPoolResponse) GetBorrowApy() int32 {
	if m != nil {
		return m.BorrowApy
	}
	return 0
}

func (m *LoadPoolResponse) GetAssetPrice() int32 {
	if m != nil {
		return m.AssetPrice
	}
	return 0
}

type LoadUserResponse struct {
	AssetApy         int32  `protobuf:"varint,1,opt,name=AssetApy,proto3" json:"AssetApy,omitempty"`
	AssetDenom       string `protobuf:"bytes,2,opt,name=AssetDenom,proto3" json:"AssetDenom,omitempty"`
	AssetBalance     int64  `protobuf:"varint,3,opt,name=AssetBalance,proto3" json:"AssetBalance,omitempty"`
	AssetDeposit     int32  `protobuf:"varint,4,opt,name=AssetDeposit,proto3" json:"AssetDeposit,omitempty"`
	AssetBorrow      int32  `protobuf:"varint,5,opt,name=AssetBorrow,proto3" json:"AssetBorrow,omitempty"`
	AssetPrice       int32  `protobuf:"varint,6,opt,name=AssetPrice,proto3" json:"AssetPrice,omitempty"`
	Collateral       bool   `protobuf:"varint,7,opt,name=Collateral,proto3" json:"Collateral,omitempty"`
	DepositEarned    int32  `protobuf:"varint,8,opt,name=DepositEarned,proto3" json:"DepositEarned,omitempty"`
	BorrowAccrued    int32  `protobuf:"varint,9,opt,name=BorrowAccrued,proto3" json:"BorrowAccrued,omitempty"`
	Asset            string `protobuf:"bytes,10,opt,name=Asset,proto3" json:"Asset,omitempty"`
	CollatoralFactor int32  `protobuf:"varint,11,opt,name=CollatoralFactor,proto3" json:"CollatoralFactor,omitempty"`
	Liquidity        int32  `protobuf:"varint,12,opt,name=Liquidity,proto3" json:"Liquidity,omitempty"`
	DepositApy       int32  `protobuf:"varint,13,opt,name=DepositApy,proto3" json:"DepositApy,omitempty"`
	BorrowApy        int32  `protobuf:"varint,14,opt,name=BorrowApy,proto3" json:"BorrowApy,omitempty"`
}

func (m *LoadUserResponse) Reset()         { *m = LoadUserResponse{} }
func (m *LoadUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoadUserResponse) ProtoMessage()    {}
func (*LoadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{1}
}
func (m *LoadUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoadUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserResponse.Merge(m, src)
}
func (m *LoadUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserResponse proto.InternalMessageInfo

func (m *LoadUserResponse) GetAssetApy() int32 {
	if m != nil {
		return m.AssetApy
	}
	return 0
}

func (m *LoadUserResponse) GetAssetDenom() string {
	if m != nil {
		return m.AssetDenom
	}
	return ""
}

func (m *LoadUserResponse) GetAssetBalance() int64 {
	if m != nil {
		return m.AssetBalance
	}
	return 0
}

func (m *LoadUserResponse) GetAssetDeposit() int32 {
	if m != nil {
		return m.AssetDeposit
	}
	return 0
}

func (m *LoadUserResponse) GetAssetBorrow() int32 {
	if m != nil {
		return m.AssetBorrow
	}
	return 0
}

func (m *LoadUserResponse) GetAssetPrice() int32 {
	if m != nil {
		return m.AssetPrice
	}
	return 0
}

func (m *LoadUserResponse) GetCollateral() bool {
	if m != nil {
		return m.Collateral
	}
	return false
}

func (m *LoadUserResponse) GetDepositEarned() int32 {
	if m != nil {
		return m.DepositEarned
	}
	return 0
}

func (m *LoadUserResponse) GetBorrowAccrued() int32 {
	if m != nil {
		return m.BorrowAccrued
	}
	return 0
}

func (m *LoadUserResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *LoadUserResponse) GetCollatoralFactor() int32 {
	if m != nil {
		return m.CollatoralFactor
	}
	return 0
}

func (m *LoadUserResponse) GetLiquidity() int32 {
	if m != nil {
		return m.Liquidity
	}
	return 0
}

func (m *LoadUserResponse) GetDepositApy() int32 {
	if m != nil {
		return m.DepositApy
	}
	return 0
}

func (m *LoadUserResponse) GetBorrowApy() int32 {
	if m != nil {
		return m.BorrowApy
	}
	return 0
}

type UserAssetBalances struct {
	Uakt  int64 `protobuf:"varint,1,opt,name=Uakt,proto3" json:"Uakt,omitempty"`
	Uatom int64 `protobuf:"varint,2,opt,name=Uatom,proto3" json:"Uatom,omitempty"`
	Ucro  int64 `protobuf:"varint,3,opt,name=Ucro,proto3" json:"Ucro,omitempty"`
	Udvpn int64 `protobuf:"varint,4,opt,name=Udvpn,proto3" json:"Udvpn,omitempty"`
	Uiris int64 `protobuf:"varint,5,opt,name=Uiris,proto3" json:"Uiris,omitempty"`
	Uxprt int64 `protobuf:"varint,6,opt,name=Uxprt,proto3" json:"Uxprt,omitempty"`
}

func (m *UserAssetBalances) Reset()         { *m = UserAssetBalances{} }
func (m *UserAssetBalances) String() string { return proto.CompactTextString(m) }
func (*UserAssetBalances) ProtoMessage()    {}
func (*UserAssetBalances) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{2}
}
func (m *UserAssetBalances) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserAssetBalances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserAssetBalances.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserAssetBalances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAssetBalances.Merge(m, src)
}
func (m *UserAssetBalances) XXX_Size() int {
	return m.Size()
}
func (m *UserAssetBalances) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAssetBalances.DiscardUnknown(m)
}

var xxx_messageInfo_UserAssetBalances proto.InternalMessageInfo

func (m *UserAssetBalances) GetUakt() int64 {
	if m != nil {
		return m.Uakt
	}
	return 0
}

func (m *UserAssetBalances) GetUatom() int64 {
	if m != nil {
		return m.Uatom
	}
	return 0
}

func (m *UserAssetBalances) GetUcro() int64 {
	if m != nil {
		return m.Ucro
	}
	return 0
}

func (m *UserAssetBalances) GetUdvpn() int64 {
	if m != nil {
		return m.Udvpn
	}
	return 0
}

func (m *UserAssetBalances) GetUiris() int64 {
	if m != nil {
		return m.Uiris
	}
	return 0
}

func (m *UserAssetBalances) GetUxprt() int64 {
	if m != nil {
		return m.Uxprt
	}
	return 0
}

type Liquidation struct {
	WalletAddress    string              `protobuf:"bytes,1,opt,name=WalletAddress,proto3" json:"WalletAddress,omitempty"`
	LiquidationAsset []*LiquidationAsset `protobuf:"bytes,2,rep,name=LiquidationAsset,proto3" json:"LiquidationAsset,omitempty"`
}

func (m *Liquidation) Reset()         { *m = Liquidation{} }
func (m *Liquidation) String() string { return proto.CompactTextString(m) }
func (*Liquidation) ProtoMessage()    {}
func (*Liquidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{3}
}
func (m *Liquidation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Liquidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Liquidation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Liquidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Liquidation.Merge(m, src)
}
func (m *Liquidation) XXX_Size() int {
	return m.Size()
}
func (m *Liquidation) XXX_DiscardUnknown() {
	xxx_messageInfo_Liquidation.DiscardUnknown(m)
}

var xxx_messageInfo_Liquidation proto.InternalMessageInfo

func (m *Liquidation) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *Liquidation) GetLiquidationAsset() []*LiquidationAsset {
	if m != nil {
		return m.LiquidationAsset
	}
	return nil
}

type LiquidationAsset struct {
	Asset  string `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (m *LiquidationAsset) Reset()         { *m = LiquidationAsset{} }
func (m *LiquidationAsset) String() string { return proto.CompactTextString(m) }
func (*LiquidationAsset) ProtoMessage()    {}
func (*LiquidationAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{4}
}
func (m *LiquidationAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationAsset.Merge(m, src)
}
func (m *LiquidationAsset) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationAsset.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationAsset proto.InternalMessageInfo

func (m *LiquidationAsset) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *LiquidationAsset) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type NftResponse struct {
	Collection        string `protobuf:"bytes,1,opt,name=Collection,proto3" json:"Collection,omitempty"`
	OwnerAddress      string `protobuf:"bytes,2,opt,name=OwnerAddress,proto3" json:"OwnerAddress,omitempty"`
	ImageUrl          string `protobuf:"bytes,3,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	Name              string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	NftCreatorAddress string `protobuf:"bytes,5,opt,name=NftCreatorAddress,proto3" json:"NftCreatorAddress,omitempty"`
	Id                int32  `protobuf:"varint,6,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *NftResponse) Reset()         { *m = NftResponse{} }
func (m *NftResponse) String() string { return proto.CompactTextString(m) }
func (*NftResponse) ProtoMessage()    {}
func (*NftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{5}
}
func (m *NftResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftResponse.Merge(m, src)
}
func (m *NftResponse) XXX_Size() int {
	return m.Size()
}
func (m *NftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NftResponse proto.InternalMessageInfo

func (m *NftResponse) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *NftResponse) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *NftResponse) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *NftResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NftResponse) GetNftCreatorAddress() string {
	if m != nil {
		return m.NftCreatorAddress
	}
	return ""
}

func (m *NftResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*LoadPoolResponse)(nil), "sapienscosmos.ibb.ibb.LoadPoolResponse")
	proto.RegisterType((*LoadUserResponse)(nil), "sapienscosmos.ibb.ibb.LoadUserResponse")
	proto.RegisterType((*UserAssetBalances)(nil), "sapienscosmos.ibb.ibb.UserAssetBalances")
	proto.RegisterType((*Liquidation)(nil), "sapienscosmos.ibb.ibb.Liquidation")
	proto.RegisterType((*LiquidationAsset)(nil), "sapienscosmos.ibb.ibb.LiquidationAsset")
	proto.RegisterType((*NftResponse)(nil), "sapienscosmos.ibb.ibb.NftResponse")
}

func init() { proto.RegisterFile("ibb/response.proto", fileDescriptor_65d3e4899842c994) }

var fileDescriptor_65d3e4899842c994 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xee, 0x24, 0x4d, 0x6d, 0x26, 0x6d, 0x69, 0x87, 0x2a, 0x4b, 0x91, 0x25, 0x2c, 0x82, 0x51,
	0x34, 0x01, 0x7d, 0x01, 0xd3, 0x56, 0xa1, 0x50, 0x6a, 0x59, 0x09, 0x82, 0x77, 0x93, 0xdd, 0x69,
	0x1c, 0xdc, 0xec, 0xac, 0x33, 0x13, 0xdb, 0xbe, 0x81, 0x97, 0x82, 0x0f, 0xe4, 0xad, 0x97, 0xbd,
	0xf4, 0x52, 0xd2, 0x17, 0x91, 0x73, 0x66, 0xba, 0xdd, 0x6d, 0xb4, 0xf5, 0x22, 0x61, 0xce, 0x37,
	0xdf, 0xf9, 0x92, 0xef, 0xfc, 0x0c, 0x65, 0x72, 0x3c, 0x1e, 0x68, 0x61, 0x0a, 0x95, 0x1b, 0xd1,
	0x2f, 0xb4, 0xb2, 0x8a, 0xdd, 0x37, 0xbc, 0x90, 0x22, 0x37, 0x89, 0x32, 0x53, 0x65, 0xfa, 0x72,
	0x3c, 0x86, 0xcf, 0xce, 0xf6, 0x44, 0x4d, 0x14, 0x32, 0x06, 0x70, 0x72, 0xe4, 0x9d, 0x0d, 0x10,
	0x98, 0x19, 0xa1, 0x5d, 0x1c, 0x5d, 0x10, 0xba, 0x79, 0xa8, 0x78, 0x7a, 0xac, 0x54, 0x16, 0x7b,
	0x5d, 0xb6, 0x4d, 0x5b, 0x43, 0x63, 0x84, 0x0d, 0x48, 0x97, 0xf4, 0xda, 0xb1, 0x0b, 0xd8, 0x53,
	0xba, 0xb9, 0xa7, 0xb2, 0x8c, 0x5b, 0xa5, 0x79, 0xf6, 0x86, 0x27, 0x56, 0xe9, 0xa0, 0xd1, 0x25,
	0xbd, 0x56, 0xbc, 0x80, 0xb3, 0x87, 0xb4, 0x7d, 0x28, 0x3f, 0xcf, 0x64, 0x2a, 0xed, 0x79, 0xd0,
	0x44, 0xd2, 0x35, 0xc0, 0x42, 0x4a, 0xf7, 0x45, 0xa1, 0x8c, 0xb4, 0xc3, 0xe2, 0x3c, 0x58, 0xc6,
	0xeb, 0x0a, 0x02, 0xd9, 0xbb, 0x4a, 0x6b, 0x75, 0x0a, 0xd7, 0x2d, 0x97, 0x5d, 0x02, 0x90, 0x8d,
	0x7f, 0xe8, 0x58, 0xcb, 0x44, 0x04, 0x2b, 0x2e, 0xfb, 0x1a, 0x89, 0xe6, 0x4d, 0x67, 0x69, 0x64,
	0x84, 0x2e, 0x2d, 0xed, 0xd0, 0x55, 0xa4, 0x80, 0x22, 0xc1, 0x94, 0x32, 0x2e, 0x05, 0xf7, 0x45,
	0xae, 0xa6, 0x68, 0xa9, 0x1d, 0x57, 0x10, 0x16, 0xd1, 0x35, 0x8c, 0x76, 0x79, 0xc6, 0xf3, 0x44,
	0xa0, 0x9f, 0x66, 0x5c, 0xc3, 0x4a, 0x8e, 0x77, 0xe1, 0x4d, 0xd5, 0x30, 0xd6, 0xa5, 0x1d, 0x97,
	0x83, 0x56, 0xbc, 0xb1, 0x2a, 0x74, 0x97, 0x35, 0xb8, 0x77, 0xa5, 0x16, 0x9a, 0x67, 0xc1, 0xbd,
	0x2e, 0xe9, 0xad, 0xc6, 0x15, 0x84, 0x3d, 0xa2, 0xeb, 0xfe, 0xc7, 0x5e, 0x73, 0x9d, 0x8b, 0x34,
	0x58, 0x45, 0x89, 0x3a, 0x08, 0x2c, 0x5f, 0xcd, 0x24, 0xd1, 0x33, 0x91, 0x06, 0x6d, 0xc7, 0xaa,
	0x81, 0xd7, 0x43, 0x40, 0xef, 0x1a, 0x82, 0xce, 0xff, 0x0c, 0xc1, 0xda, 0xed, 0x43, 0xb0, 0x7e,
	0xfb, 0x10, 0x6c, 0xdc, 0x18, 0x82, 0xe8, 0x3b, 0xa1, 0x5b, 0xd0, 0xe0, 0x6a, 0x13, 0x0c, 0x63,
	0x74, 0x79, 0xc4, 0x3f, 0xb9, 0xb9, 0x6d, 0xc6, 0x78, 0x06, 0x1f, 0x23, 0x6e, 0x7d, 0x63, 0x9b,
	0xb1, 0x0b, 0x90, 0x99, 0x68, 0xe5, 0x7b, 0x89, 0x67, 0x64, 0xa6, 0x5f, 0x8a, 0x1c, 0x9b, 0x07,
	0x4c, 0x08, 0x10, 0x95, 0x5a, 0x1a, 0xec, 0x17, 0xa0, 0x10, 0x20, 0x7a, 0x56, 0x68, 0x8b, 0x4d,
	0x02, 0x14, 0x82, 0xe8, 0x2b, 0xa1, 0x1d, 0xe7, 0x90, 0x5b, 0xa9, 0x72, 0xa8, 0xf4, 0x7b, 0x9e,
	0x65, 0xc2, 0x0e, 0xd3, 0x54, 0x0b, 0x63, 0xfc, 0x42, 0xd5, 0x41, 0xf6, 0x8e, 0x6e, 0x56, 0x92,
	0x5c, 0xd1, 0x1b, 0xdd, 0x66, 0xaf, 0xf3, 0xe2, 0x71, 0xff, 0xaf, 0xbb, 0xdd, 0xbf, 0x49, 0x8f,
	0x17, 0x04, 0xa2, 0x57, 0x8b, 0xa2, 0xff, 0xd8, 0xeb, 0x07, 0x74, 0x65, 0x38, 0x55, 0xb3, 0xdc,
	0xfa, 0x0a, 0xf9, 0x28, 0xfa, 0x41, 0x68, 0xe7, 0xe8, 0xc4, 0x96, 0x2b, 0xe4, 0x87, 0x4f, 0x24,
	0x20, 0xe8, 0x25, 0x2a, 0x08, 0xac, 0xc0, 0xdb, 0xd3, 0x5c, 0xe8, 0x2b, 0xaf, 0x6e, 0x91, 0x6a,
	0x18, 0xac, 0xe1, 0xc1, 0x94, 0x4f, 0xc4, 0x48, 0x67, 0x58, 0xfa, 0x76, 0x5c, 0xc6, 0xd0, 0x92,
	0x23, 0x3e, 0x15, 0x58, 0xfd, 0x76, 0x8c, 0x67, 0xf6, 0x8c, 0x6e, 0x1d, 0x9d, 0xd8, 0x3d, 0x2d,
	0x60, 0xb0, 0xae, 0x84, 0x5b, 0x48, 0x58, 0xbc, 0x60, 0x1b, 0xb4, 0x71, 0x90, 0xfa, 0xb5, 0x69,
	0x1c, 0xa4, 0xbb, 0x7b, 0x3f, 0xe7, 0x21, 0xb9, 0x98, 0x87, 0xe4, 0xf7, 0x3c, 0x24, 0xdf, 0x2e,
	0xc3, 0xa5, 0x8b, 0xcb, 0x70, 0xe9, 0xd7, 0x65, 0xb8, 0xf4, 0xe1, 0xc9, 0x44, 0xda, 0x8f, 0xb3,
	0x71, 0x3f, 0x51, 0xd3, 0x81, 0x2f, 0xf1, 0x73, 0x57, 0xe3, 0x01, 0x3c, 0x90, 0x67, 0xf8, 0x6d,
	0xcf, 0x0b, 0x61, 0xc6, 0x2b, 0xf8, 0x50, 0xbe, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x67,
	0x09, 0x65, 0x7b, 0x05, 0x00, 0x00,
}

func (m *LoadPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoadPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoadPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AssetPrice != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetPrice))
		i--
		dAtA[i] = 0x30
	}
	if m.BorrowApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.BorrowApy))
		i--
		dAtA[i] = 0x28
	}
	if m.DepositApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.DepositApy))
		i--
		dAtA[i] = 0x20
	}
	if m.Liquidity != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Liquidity))
		i--
		dAtA[i] = 0x18
	}
	if m.CollatoralFactor != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.CollatoralFactor))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoadUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoadUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoadUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BorrowApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.BorrowApy))
		i--
		dAtA[i] = 0x70
	}
	if m.DepositApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.DepositApy))
		i--
		dAtA[i] = 0x68
	}
	if m.Liquidity != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Liquidity))
		i--
		dAtA[i] = 0x60
	}
	if m.CollatoralFactor != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.CollatoralFactor))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0x52
	}
	if m.BorrowAccrued != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.BorrowAccrued))
		i--
		dAtA[i] = 0x48
	}
	if m.DepositEarned != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.DepositEarned))
		i--
		dAtA[i] = 0x40
	}
	if m.Collateral {
		i--
		if m.Collateral {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.AssetPrice != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetPrice))
		i--
		dAtA[i] = 0x30
	}
	if m.AssetBorrow != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetBorrow))
		i--
		dAtA[i] = 0x28
	}
	if m.AssetDeposit != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetDeposit))
		i--
		dAtA[i] = 0x20
	}
	if m.AssetBalance != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetBalance))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AssetDenom) > 0 {
		i -= len(m.AssetDenom)
		copy(dAtA[i:], m.AssetDenom)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.AssetDenom)))
		i--
		dAtA[i] = 0x12
	}
	if m.AssetApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetApy))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UserAssetBalances) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserAssetBalances) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserAssetBalances) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Uxprt != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Uxprt))
		i--
		dAtA[i] = 0x30
	}
	if m.Uiris != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Uiris))
		i--
		dAtA[i] = 0x28
	}
	if m.Udvpn != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Udvpn))
		i--
		dAtA[i] = 0x20
	}
	if m.Ucro != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Ucro))
		i--
		dAtA[i] = 0x18
	}
	if m.Uatom != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Uatom))
		i--
		dAtA[i] = 0x10
	}
	if m.Uakt != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Uakt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Liquidation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Liquidation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Liquidation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LiquidationAsset) > 0 {
		for iNdEx := len(m.LiquidationAsset) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidationAsset[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintResponse(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.WalletAddress) > 0 {
		i -= len(m.WalletAddress)
		copy(dAtA[i:], m.WalletAddress)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.WalletAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LiquidationAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x30
	}
	if len(m.NftCreatorAddress) > 0 {
		i -= len(m.NftCreatorAddress)
		copy(dAtA[i:], m.NftCreatorAddress)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.NftCreatorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ImageUrl) > 0 {
		i -= len(m.ImageUrl)
		copy(dAtA[i:], m.ImageUrl)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.ImageUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Collection) > 0 {
		i -= len(m.Collection)
		copy(dAtA[i:], m.Collection)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Collection)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintResponse(dAtA []byte, offset int, v uint64) int {
	offset -= sovResponse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoadPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.CollatoralFactor != 0 {
		n += 1 + sovResponse(uint64(m.CollatoralFactor))
	}
	if m.Liquidity != 0 {
		n += 1 + sovResponse(uint64(m.Liquidity))
	}
	if m.DepositApy != 0 {
		n += 1 + sovResponse(uint64(m.DepositApy))
	}
	if m.BorrowApy != 0 {
		n += 1 + sovResponse(uint64(m.BorrowApy))
	}
	if m.AssetPrice != 0 {
		n += 1 + sovResponse(uint64(m.AssetPrice))
	}
	return n
}

func (m *LoadUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetApy != 0 {
		n += 1 + sovResponse(uint64(m.AssetApy))
	}
	l = len(m.AssetDenom)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.AssetBalance != 0 {
		n += 1 + sovResponse(uint64(m.AssetBalance))
	}
	if m.AssetDeposit != 0 {
		n += 1 + sovResponse(uint64(m.AssetDeposit))
	}
	if m.AssetBorrow != 0 {
		n += 1 + sovResponse(uint64(m.AssetBorrow))
	}
	if m.AssetPrice != 0 {
		n += 1 + sovResponse(uint64(m.AssetPrice))
	}
	if m.Collateral {
		n += 2
	}
	if m.DepositEarned != 0 {
		n += 1 + sovResponse(uint64(m.DepositEarned))
	}
	if m.BorrowAccrued != 0 {
		n += 1 + sovResponse(uint64(m.BorrowAccrued))
	}
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.CollatoralFactor != 0 {
		n += 1 + sovResponse(uint64(m.CollatoralFactor))
	}
	if m.Liquidity != 0 {
		n += 1 + sovResponse(uint64(m.Liquidity))
	}
	if m.DepositApy != 0 {
		n += 1 + sovResponse(uint64(m.DepositApy))
	}
	if m.BorrowApy != 0 {
		n += 1 + sovResponse(uint64(m.BorrowApy))
	}
	return n
}

func (m *UserAssetBalances) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Uakt != 0 {
		n += 1 + sovResponse(uint64(m.Uakt))
	}
	if m.Uatom != 0 {
		n += 1 + sovResponse(uint64(m.Uatom))
	}
	if m.Ucro != 0 {
		n += 1 + sovResponse(uint64(m.Ucro))
	}
	if m.Udvpn != 0 {
		n += 1 + sovResponse(uint64(m.Udvpn))
	}
	if m.Uiris != 0 {
		n += 1 + sovResponse(uint64(m.Uiris))
	}
	if m.Uxprt != 0 {
		n += 1 + sovResponse(uint64(m.Uxprt))
	}
	return n
}

func (m *Liquidation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WalletAddress)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if len(m.LiquidationAsset) > 0 {
		for _, e := range m.LiquidationAsset {
			l = e.Size()
			n += 1 + l + sovResponse(uint64(l))
		}
	}
	return n
}

func (m *LiquidationAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovResponse(uint64(m.Amount))
	}
	return n
}

func (m *NftResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Collection)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.ImageUrl)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.NftCreatorAddress)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovResponse(uint64(m.Id))
	}
	return n
}

func sovResponse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResponse(x uint64) (n int) {
	return sovResponse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LoadPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoadPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoadPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollatoralFactor", wireType)
			}
			m.CollatoralFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollatoralFactor |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidity", wireType)
			}
			m.Liquidity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Liquidity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositApy", wireType)
			}
			m.DepositApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowApy", wireType)
			}
			m.BorrowApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetPrice", wireType)
			}
			m.AssetPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetPrice |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoadUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoadUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoadUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetApy", wireType)
			}
			m.AssetApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetBalance", wireType)
			}
			m.AssetBalance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetBalance |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDeposit", wireType)
			}
			m.AssetDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetDeposit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetBorrow", wireType)
			}
			m.AssetBorrow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetBorrow |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetPrice", wireType)
			}
			m.AssetPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetPrice |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Collateral = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositEarned", wireType)
			}
			m.DepositEarned = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositEarned |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowAccrued", wireType)
			}
			m.BorrowAccrued = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowAccrued |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollatoralFactor", wireType)
			}
			m.CollatoralFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollatoralFactor |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidity", wireType)
			}
			m.Liquidity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Liquidity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositApy", wireType)
			}
			m.DepositApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowApy", wireType)
			}
			m.BorrowApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserAssetBalances) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserAssetBalances: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserAssetBalances: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uakt", wireType)
			}
			m.Uakt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uakt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uatom", wireType)
			}
			m.Uatom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uatom |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ucro", wireType)
			}
			m.Ucro = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ucro |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Udvpn", wireType)
			}
			m.Udvpn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Udvpn |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uiris", wireType)
			}
			m.Uiris = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uiris |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uxprt", wireType)
			}
			m.Uxprt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uxprt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Liquidation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Liquidation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Liquidation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationAsset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationAsset = append(m.LiquidationAsset, &LiquidationAsset{})
			if err := m.LiquidationAsset[len(m.LiquidationAsset)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidationAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCreatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftCreatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResponse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResponse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResponse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResponse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResponse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResponse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResponse = fmt.Errorf("proto: unexpected end of group")
)
