// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibb/response.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LoadPoolResponse struct {
	Asset            string `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	CollatoralFactor int32  `protobuf:"varint,2,opt,name=CollatoralFactor,proto3" json:"CollatoralFactor,omitempty"`
	Liquidity        int32  `protobuf:"varint,3,opt,name=Liquidity,proto3" json:"Liquidity,omitempty"`
	DepositApy       int32  `protobuf:"varint,4,opt,name=DepositApy,proto3" json:"DepositApy,omitempty"`
	BorrowApy        int32  `protobuf:"varint,5,opt,name=BorrowApy,proto3" json:"BorrowApy,omitempty"`
}

func (m *LoadPoolResponse) Reset()         { *m = LoadPoolResponse{} }
func (m *LoadPoolResponse) String() string { return proto.CompactTextString(m) }
func (*LoadPoolResponse) ProtoMessage()    {}
func (*LoadPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{0}
}
func (m *LoadPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoadPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoadPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoadPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPoolResponse.Merge(m, src)
}
func (m *LoadPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoadPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPoolResponse proto.InternalMessageInfo

func (m *LoadPoolResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *LoadPoolResponse) GetCollatoralFactor() int32 {
	if m != nil {
		return m.CollatoralFactor
	}
	return 0
}

func (m *LoadPoolResponse) GetLiquidity() int32 {
	if m != nil {
		return m.Liquidity
	}
	return 0
}

func (m *LoadPoolResponse) GetDepositApy() int32 {
	if m != nil {
		return m.DepositApy
	}
	return 0
}

func (m *LoadPoolResponse) GetBorrowApy() int32 {
	if m != nil {
		return m.BorrowApy
	}
	return 0
}

type LoadUserResponse struct {
	AssetApy     int32  `protobuf:"varint,1,opt,name=AssetApy,proto3" json:"AssetApy,omitempty"`
	AssetDenom   string `protobuf:"bytes,2,opt,name=AssetDenom,proto3" json:"AssetDenom,omitempty"`
	AssetBalance int64  `protobuf:"varint,3,opt,name=AssetBalance,proto3" json:"AssetBalance,omitempty"`
	AssetDeposit int32  `protobuf:"varint,4,opt,name=AssetDeposit,proto3" json:"AssetDeposit,omitempty"`
	AssetBorrow  int32  `protobuf:"varint,5,opt,name=AssetBorrow,proto3" json:"AssetBorrow,omitempty"`
	AssetPrice   int32  `protobuf:"varint,6,opt,name=AssetPrice,proto3" json:"AssetPrice,omitempty"`
	Collateral   bool   `protobuf:"varint,7,opt,name=Collateral,proto3" json:"Collateral,omitempty"`
}

func (m *LoadUserResponse) Reset()         { *m = LoadUserResponse{} }
func (m *LoadUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoadUserResponse) ProtoMessage()    {}
func (*LoadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d3e4899842c994, []int{1}
}
func (m *LoadUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoadUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserResponse.Merge(m, src)
}
func (m *LoadUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserResponse proto.InternalMessageInfo

func (m *LoadUserResponse) GetAssetApy() int32 {
	if m != nil {
		return m.AssetApy
	}
	return 0
}

func (m *LoadUserResponse) GetAssetDenom() string {
	if m != nil {
		return m.AssetDenom
	}
	return ""
}

func (m *LoadUserResponse) GetAssetBalance() int64 {
	if m != nil {
		return m.AssetBalance
	}
	return 0
}

func (m *LoadUserResponse) GetAssetDeposit() int32 {
	if m != nil {
		return m.AssetDeposit
	}
	return 0
}

func (m *LoadUserResponse) GetAssetBorrow() int32 {
	if m != nil {
		return m.AssetBorrow
	}
	return 0
}

func (m *LoadUserResponse) GetAssetPrice() int32 {
	if m != nil {
		return m.AssetPrice
	}
	return 0
}

func (m *LoadUserResponse) GetCollateral() bool {
	if m != nil {
		return m.Collateral
	}
	return false
}

func init() {
	proto.RegisterType((*LoadPoolResponse)(nil), "sapienscosmos.ibb.ibb.LoadPoolResponse")
	proto.RegisterType((*LoadUserResponse)(nil), "sapienscosmos.ibb.ibb.LoadUserResponse")
}

func init() { proto.RegisterFile("ibb/response.proto", fileDescriptor_65d3e4899842c994) }

var fileDescriptor_65d3e4899842c994 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcd, 0x6a, 0xf2, 0x40,
	0x14, 0x86, 0x9d, 0xcf, 0x4f, 0xab, 0xd3, 0x52, 0x64, 0xb0, 0x10, 0xa4, 0x0c, 0xc1, 0x95, 0x2d,
	0xd4, 0x2c, 0x7a, 0x05, 0xfe, 0xd0, 0x95, 0x0b, 0x09, 0x74, 0xd3, 0xdd, 0x24, 0x0e, 0x76, 0x20,
	0xe6, 0xa4, 0x33, 0x23, 0xad, 0x77, 0xd1, 0x4b, 0xe9, 0x65, 0x74, 0xe9, 0xb2, 0xcb, 0x62, 0x6e,
	0xa2, 0xcb, 0x32, 0x3f, 0xc4, 0x48, 0x17, 0xca, 0x9c, 0xe7, 0x9c, 0x77, 0xf2, 0x24, 0x33, 0x98,
	0x88, 0x24, 0x89, 0x24, 0x57, 0x05, 0xe4, 0x8a, 0x8f, 0x0b, 0x09, 0x1a, 0xc8, 0x95, 0x62, 0x85,
	0xe0, 0xb9, 0x4a, 0x41, 0x6d, 0x40, 0x8d, 0x45, 0x92, 0x98, 0xdf, 0xa0, 0xbf, 0x86, 0x35, 0xd8,
	0x89, 0xc8, 0xac, 0xdc, 0xf0, 0xe0, 0xd2, 0x6c, 0xb0, 0x55, 0x5c, 0xba, 0x7a, 0xf8, 0x81, 0x70,
	0x6f, 0x01, 0x6c, 0xb5, 0x04, 0xc8, 0x62, 0xbf, 0x2f, 0xe9, 0xe3, 0xd6, 0x44, 0x29, 0xae, 0x03,
	0x14, 0xa2, 0x51, 0x37, 0x76, 0x05, 0xb9, 0xc5, 0xbd, 0x19, 0x64, 0x19, 0xd3, 0x20, 0x59, 0xf6,
	0xc0, 0x52, 0x0d, 0x32, 0xf8, 0x17, 0xa2, 0x51, 0x2b, 0xfe, 0xc3, 0xc9, 0x35, 0xee, 0x2e, 0xc4,
	0xcb, 0x56, 0xac, 0x84, 0xde, 0x05, 0x4d, 0x3b, 0x74, 0x04, 0x84, 0x62, 0x3c, 0xe7, 0x05, 0x28,
	0xa1, 0x27, 0xc5, 0x2e, 0xf8, 0x6f, 0xdb, 0x35, 0x62, 0xd2, 0x53, 0x90, 0x12, 0x5e, 0x4d, 0xbb,
	0xe5, 0xd2, 0x15, 0x18, 0xfe, 0x78, 0xe5, 0x47, 0xc5, 0x65, 0xa5, 0x3c, 0xc0, 0x1d, 0x6b, 0x69,
	0x12, 0xc8, 0x26, 0xaa, 0xda, 0x3c, 0xce, 0xae, 0xe7, 0x3c, 0x87, 0x8d, 0x55, 0xee, 0xc6, 0x35,
	0x42, 0x86, 0xf8, 0xc2, 0x56, 0x53, 0x96, 0xb1, 0x3c, 0xe5, 0xd6, 0xb7, 0x19, 0x9f, 0xb0, 0x6a,
	0xc6, 0x5b, 0x7a, 0xe9, 0x13, 0x46, 0x42, 0x7c, 0xee, 0x32, 0x56, 0xd5, 0x8b, 0xd7, 0x51, 0x65,
	0xb2, 0x94, 0x22, 0xe5, 0x41, 0xdb, 0xbd, 0xf8, 0x91, 0x98, 0xbe, 0xfb, 0x94, 0x5c, 0xb2, 0x2c,
	0x38, 0x0b, 0xd1, 0xa8, 0x13, 0xd7, 0xc8, 0x74, 0xf6, 0x79, 0xa0, 0x68, 0x7f, 0xa0, 0xe8, 0xfb,
	0x40, 0xd1, 0x7b, 0x49, 0x1b, 0xfb, 0x92, 0x36, 0xbe, 0x4a, 0xda, 0x78, 0xba, 0x59, 0x0b, 0xfd,
	0xbc, 0x4d, 0xc6, 0x29, 0x6c, 0x22, 0x7f, 0x1f, 0xee, 0xdc, 0x85, 0x88, 0xcc, 0x89, 0xbf, 0xd9,
	0x7f, 0xbd, 0x2b, 0xb8, 0x4a, 0xda, 0xf6, 0xe4, 0xef, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x06,
	0xa9, 0x7a, 0x59, 0x4c, 0x02, 0x00, 0x00,
}

func (m *LoadPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoadPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoadPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BorrowApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.BorrowApy))
		i--
		dAtA[i] = 0x28
	}
	if m.DepositApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.DepositApy))
		i--
		dAtA[i] = 0x20
	}
	if m.Liquidity != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.Liquidity))
		i--
		dAtA[i] = 0x18
	}
	if m.CollatoralFactor != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.CollatoralFactor))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoadUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoadUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoadUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Collateral {
		i--
		if m.Collateral {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.AssetPrice != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetPrice))
		i--
		dAtA[i] = 0x30
	}
	if m.AssetBorrow != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetBorrow))
		i--
		dAtA[i] = 0x28
	}
	if m.AssetDeposit != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetDeposit))
		i--
		dAtA[i] = 0x20
	}
	if m.AssetBalance != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetBalance))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AssetDenom) > 0 {
		i -= len(m.AssetDenom)
		copy(dAtA[i:], m.AssetDenom)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.AssetDenom)))
		i--
		dAtA[i] = 0x12
	}
	if m.AssetApy != 0 {
		i = encodeVarintResponse(dAtA, i, uint64(m.AssetApy))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintResponse(dAtA []byte, offset int, v uint64) int {
	offset -= sovResponse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoadPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.CollatoralFactor != 0 {
		n += 1 + sovResponse(uint64(m.CollatoralFactor))
	}
	if m.Liquidity != 0 {
		n += 1 + sovResponse(uint64(m.Liquidity))
	}
	if m.DepositApy != 0 {
		n += 1 + sovResponse(uint64(m.DepositApy))
	}
	if m.BorrowApy != 0 {
		n += 1 + sovResponse(uint64(m.BorrowApy))
	}
	return n
}

func (m *LoadUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetApy != 0 {
		n += 1 + sovResponse(uint64(m.AssetApy))
	}
	l = len(m.AssetDenom)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	if m.AssetBalance != 0 {
		n += 1 + sovResponse(uint64(m.AssetBalance))
	}
	if m.AssetDeposit != 0 {
		n += 1 + sovResponse(uint64(m.AssetDeposit))
	}
	if m.AssetBorrow != 0 {
		n += 1 + sovResponse(uint64(m.AssetBorrow))
	}
	if m.AssetPrice != 0 {
		n += 1 + sovResponse(uint64(m.AssetPrice))
	}
	if m.Collateral {
		n += 2
	}
	return n
}

func sovResponse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResponse(x uint64) (n int) {
	return sovResponse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LoadPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoadPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoadPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollatoralFactor", wireType)
			}
			m.CollatoralFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollatoralFactor |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidity", wireType)
			}
			m.Liquidity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Liquidity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositApy", wireType)
			}
			m.DepositApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowApy", wireType)
			}
			m.BorrowApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoadUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoadUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoadUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetApy", wireType)
			}
			m.AssetApy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetApy |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetBalance", wireType)
			}
			m.AssetBalance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetBalance |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDeposit", wireType)
			}
			m.AssetDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetDeposit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetBorrow", wireType)
			}
			m.AssetBorrow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetBorrow |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetPrice", wireType)
			}
			m.AssetPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetPrice |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Collateral = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResponse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResponse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResponse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResponse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResponse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResponse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResponse = fmt.Errorf("proto: unexpected end of group")
)
