// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibb/user.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id           uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Collateral   bool   `protobuf:"varint,3,opt,name=collateral,proto3" json:"collateral,omitempty"`
	TotalDeposit int32  `protobuf:"varint,4,opt,name=totalDeposit,proto3" json:"totalDeposit,omitempty"`
	TotalBorrow  int32  `protobuf:"varint,5,opt,name=totalBorrow,proto3" json:"totalBorrow,omitempty"`
	Deposit      int32  `protobuf:"varint,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Borrow       string `protobuf:"bytes,7,opt,name=borrow,proto3" json:"borrow,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc30c3e3fcf9ee8e, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_User.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return m.Size()
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetCollateral() bool {
	if m != nil {
		return m.Collateral
	}
	return false
}

func (m *User) GetTotalDeposit() int32 {
	if m != nil {
		return m.TotalDeposit
	}
	return 0
}

func (m *User) GetTotalBorrow() int32 {
	if m != nil {
		return m.TotalBorrow
	}
	return 0
}

func (m *User) GetDeposit() int32 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *User) GetBorrow() string {
	if m != nil {
		return m.Borrow
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "sapienscosmos.ibb.ibb.User")
}

func init() { proto.RegisterFile("ibb/user.proto", fileDescriptor_cc30c3e3fcf9ee8e) }

var fileDescriptor_cc30c3e3fcf9ee8e = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xe3, 0x90, 0xa6, 0xf0, 0x40, 0x1d, 0x2c, 0x40, 0x16, 0x83, 0x65, 0x75, 0x0a, 0x03,
	0xc9, 0xc0, 0x0d, 0x0a, 0x27, 0x88, 0xc4, 0xc2, 0x66, 0x27, 0x56, 0xb0, 0x94, 0xf2, 0x22, 0xdb,
	0x15, 0x70, 0x0b, 0x8e, 0xd5, 0xb1, 0x23, 0x23, 0x4a, 0x2e, 0x82, 0xe2, 0xa4, 0x52, 0x19, 0x6c,
	0xf9, 0xfb, 0xfd, 0xdb, 0x7a, 0xfa, 0x60, 0x65, 0x94, 0x2a, 0x76, 0x4e, 0xdb, 0xbc, 0xb3, 0xe8,
	0x91, 0xde, 0x38, 0xd9, 0x19, 0xfd, 0xee, 0x2a, 0x74, 0x5b, 0x74, 0xb9, 0x51, 0x6a, 0x5c, 0x77,
	0xd7, 0x0d, 0x36, 0x18, 0x1a, 0xc5, 0x78, 0x9a, 0xca, 0xeb, 0x3d, 0x81, 0xe4, 0xc5, 0x69, 0x4b,
	0x19, 0x2c, 0x2b, 0xab, 0xa5, 0x47, 0xcb, 0x88, 0x20, 0xd9, 0x45, 0x79, 0x44, 0xba, 0x82, 0xd8,
	0xd4, 0x2c, 0x16, 0x24, 0x4b, 0xca, 0xd8, 0xd4, 0x94, 0x03, 0x54, 0xd8, 0xb6, 0xd2, 0x6b, 0x2b,
	0x5b, 0x76, 0x26, 0x48, 0x76, 0x5e, 0x9e, 0x24, 0x74, 0x0d, 0x57, 0x1e, 0xbd, 0x6c, 0x9f, 0x75,
	0x87, 0xce, 0x78, 0x96, 0x08, 0x92, 0x2d, 0xca, 0x7f, 0x19, 0x15, 0x70, 0x19, 0x78, 0x83, 0xd6,
	0xe2, 0x07, 0x5b, 0x84, 0xca, 0x69, 0x34, 0xce, 0x53, 0xcf, 0x1f, 0xa4, 0xe1, 0xf6, 0x88, 0xf4,
	0x16, 0x52, 0x35, 0x3d, 0x5b, 0x86, 0x41, 0x67, 0xda, 0x3c, 0xed, 0x7b, 0x4e, 0x0e, 0x3d, 0x27,
	0xbf, 0x3d, 0x27, 0xdf, 0x03, 0x8f, 0x0e, 0x03, 0x8f, 0x7e, 0x06, 0x1e, 0xbd, 0xde, 0x37, 0xc6,
	0xbf, 0xed, 0x54, 0x5e, 0xe1, 0xb6, 0x98, 0xe5, 0x3c, 0x4c, 0x76, 0x8a, 0xd1, 0xdd, 0x67, 0xd8,
	0xfd, 0x57, 0xa7, 0x9d, 0x4a, 0x83, 0x96, 0xc7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xb7,
	0x5a, 0x4f, 0x55, 0x01, 0x00, 0x00,
}

func (m *User) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *User) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *User) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Borrow) > 0 {
		i -= len(m.Borrow)
		copy(dAtA[i:], m.Borrow)
		i = encodeVarintUser(dAtA, i, uint64(len(m.Borrow)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Deposit != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.Deposit))
		i--
		dAtA[i] = 0x30
	}
	if m.TotalBorrow != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.TotalBorrow))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalDeposit != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.TotalDeposit))
		i--
		dAtA[i] = 0x20
	}
	if m.Collateral {
		i--
		if m.Collateral {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintUser(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUser(dAtA []byte, offset int, v uint64) int {
	offset -= sovUser(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *User) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovUser(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovUser(uint64(m.Id))
	}
	if m.Collateral {
		n += 2
	}
	if m.TotalDeposit != 0 {
		n += 1 + sovUser(uint64(m.TotalDeposit))
	}
	if m.TotalBorrow != 0 {
		n += 1 + sovUser(uint64(m.TotalBorrow))
	}
	if m.Deposit != 0 {
		n += 1 + sovUser(uint64(m.Deposit))
	}
	l = len(m.Borrow)
	if l > 0 {
		n += 1 + l + sovUser(uint64(l))
	}
	return n
}

func sovUser(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUser(x uint64) (n int) {
	return sovUser(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *User) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: User: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Collateral = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDeposit", wireType)
			}
			m.TotalDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalDeposit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBorrow", wireType)
			}
			m.TotalBorrow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBorrow |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			m.Deposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deposit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrow = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUser(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUser
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUser
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUser
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUser
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUser        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUser          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUser = fmt.Errorf("proto: unexpected end of group")
)
